### DISCUSSION TITLE
What are you using in production?

### DISCUSSION THREAD

**Discussion by robertoassuncaofilho** [cookiecutter/cookiecutter-django#3419] [Q&A] [answered]
When you develop a new project using django cookiecutter, what do you use for production deployments?
Currently (after my first project developed using django cookiecutter), I am using docker-compose on a Linux-based VM at DigitalOcean (a droplet), but I realized that it is a bad idea (on every new release, it takes about 3 to 5 minutes of downtime at my server).
I believe that Kubernetes would be a better option, but honestly, I need to study it.
I would appreciate it if you can share your experience and any tip about production environments for cookiecutter projects.

**Comment by foarsitter** [comment, marked as answer]
Can you describe your release proces? I do the same once a while and in my situation it does not take 3 to 5 minutes to deploy a new version. There is some downtime but not more than 60 seconds I think.

The actual update command I use is `docker-compose -f production.yml up -d django celeryworker`. Before I run that command I pull the new images from a registry and run the migrations with the new image. Before I was using an online registry I was building the images on the server which caused a lot of trouble. 

Nowadays I make use of a single VPS (4cpu, 8gb ram) to host a docker-swarm instance for multiple sites and apps. There is an excellent tutorial about this on https://dockerswarm.rocks/. In swarm mode you can use the `restart_policy` definition with an `healthcheck` command as shown below. This enables you to perform rolling updates with the command `docker service update <service_name> --image <image_name>`. 

```yml
services:
  django:
    <<: *default-opts    
    command: /start

    healthcheck:
      test: /bin/bash -c "timeout 1 bash -c '</dev/tcp/localhost/5000' 2>/dev/null"
      start_period: 20s
      interval: 30s
      timeout: 30s
      retries: 5
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 24
      rollback_config:
        parallelism: 0
        order: stop-first
      update_config:
         order: start-first
         failure_action: rollback
         delay: 10s 
```
