### DISCUSSION TITLE
Waiting for PostgreSQL to become available...

### DISCUSSION THREAD

**Discussion by gamesbook** [cookiecutter/cookiecutter-django#3580] [Q&A] [answered]
My project works with the `runserver` but when I try to bring up the Dockerised version, the logs show this:
```
postgres_1  | PostgreSQL init process complete; ready for start up.

postgres_1  | PostgreSQL init process complete; ready for start up.
postgres_1  | 
postgres_1  | 2022-02-09 09:55:03.782 UTC [1] LOG:  starting PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
postgres_1  | 2022-02-09 09:55:03.782 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2022-02-09 09:55:03.782 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2022-02-09 09:55:03.788 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2022-02-09 09:55:03.795 UTC [74] LOG:  database system was shut down at 2022-02-09 09:55:03 UTC
postgres_1  | 2022-02-09 09:55:03.800 UTC [1] LOG:  database system is ready to accept connections
django_1    | Waiting for PostgreSQL to become available...
django_1    | Waiting for PostgreSQL to become available..
```
And that last log line just keeps repeating.

What could be the cause and how do I debug/fix this?

**Comment by foarsitter** [comment]
What is your value for the `POSTGRES_HOST` environment variable? Since postgres now runs in a container you need to reference the name of that service as defined in your `local.yml` compose file (`postgres` in the case of a new project). 

If the value is `localhost` as I expect, the django container will try to connect to the localhost INSIDE the container and does not find anything there on port 5432.

**Comment by gamesbook** [comment]
The postgres section of the YML file is:
```
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: test_production_postgres
    container_name: test_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5544:5432"
 ```
and the `.postgres` file has:
```
# PostgreSQL
# ------------------------------------------------------------------------------
POSTGRES_HOST=postgres
POSTGRES_PORT=5544
POSTGRES_DB=test
POSTGRES_USER=test
POSTGRES_PASSWORD=pass123
```
