### DISCUSSION TITLE
Struggling to Deploy to Digital Ocean with GitHub Actions and Docker

### DISCUSSION THREAD

**Discussion by Spiewart** [cookiecutter/cookiecutter-django#4741] [Q&A]
Hi all, as said, I'm really struggling to deploy my Cookiecutter application to Digital Ocean with GitHub Actions and Docker.

I utilized the GitHub Actions project option, and the CI runs as expected.

I have a staging service that builds and updates my containers to GitHub Actions. This succeeds.

The issue is when I deploy, I pull my containers from GitHub Actions into my DigitalOcean droplet and copy the production.yml file. However, when I run it, the relative paths fail to find all the necessary nested files (Dockerfiles, gulpfile.js, etc.) I manually imported my .envs folder from GitHub secrets.

I followed this [demo](https://testdriven.io/blog/deploying-django-to-digitalocean-with-docker-and-github-actions/) and modified the code to suit my project. 

The relevant .yml files are listed below. Any help on overcoming this very persistent bottleneck is much appreciated. I am very new to docker, let alone a complicated project structure like this one. 

Thanks.

cd.yml part 1
```
name: CD

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  # Set global variables for the images
  WEB_IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/web
  TRAEFIK_IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/traefik
  POSTGRES_IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/postgres

on:
  pull_request:
    branches: ['master', 'main']
    paths-ignore: ['docs/**']

  push:
    branches: ['master', 'main']
    paths-ignore: ['docs/**']

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  quality-assurance:
    name: Quality Assurance
    uses: ./.github/workflows/ci.yml

  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
      - name: Set environment variables
        run: |
          echo "WEB_IMAGE=$(echo ${{ env.WEB_IMAGE }} )" >> $GITHUB_ENV
          echo "TRAEFIK_IMAGE=$(echo ${{ env.TRAEFIK_IMAGE }} )" >> $GITHUB_ENV
          echo "POSTGRES_IMAGE=$(echo ${{ env.POSTGRES_IMAGE }} )" >> $GITHUB_ENV
          mkdir -p .envs/.production
          echo "${{secrets.MYWEBAPP_DJANGO_ENV_BUILD }}" >> .envs/.production/.django
          echo "${{secrets.MYWEBAPP_POSTGRES_ENV_BUILD }}" >> .envs/.production/.postgres
      - name: Log in to GitHub Packages
        run: echo ${PERSONAL_ACCESS_TOKEN} | docker login ghcr.io -u ${{ secrets.NAMESPACE }} --password-stdin
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Pull images
        run: |
          docker pull ${{ env.WEB_IMAGE }} || true
          docker pull ${{ env.TRAEFIK_IMAGE }} || true
          docker pull ${{ env.POSTGRES_IMAGE }} || true
      - name: Build images
        run: |
          docker compose -f staging.yml build
      - name: Tag images
        run: |
          docker tag mywebapp_production_django ${{ env.WEB_IMAGE }}:latest
          docker tag mywebapp_production_traefik ${{ env.TRAEFIK_IMAGE }}:latest
          docker tag mywebapp_production_postgres ${{ env.POSTGRES_IMAGE }}:latest
      - name: Push images
        run: |
          docker push ${{ env.WEB_IMAGE }}
          docker push ${{ env.TRAEFIK_IMAGE }}
          docker push ${{ env.POSTGRES_IMAGE }}

  deploy:
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - name: Add environment variables to .env
        run: |
          echo "WEB_IMAGE=$(echo ${{ env.WEB_IMAGE }} )" >> .env
          echo "TRAEFIK_IMAGE=$(echo ${{ env.TRAEFIK_IMAGE }} )" >> .env
          echo "POSTGRES_IMAGE=$(echo ${{ env.POSTGRES_IMAGE }} )" >> .env
          echo NAMESPACE=${{ secrets.NAMESPACE }} >> .env
          echo PERSONAL_ACCESS_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }} >> .env
      - name: Add the private SSH key to the ssh-agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-add - <<< "${{ secrets.PRIVATE_KEY }}"
      - name: Build and deploy images on DigitalOcean
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          scp -o StrictHostKeyChecking=no -r ./.env ./production.yml root@${{ secrets.DIGITAL_OCEAN_IP_ADDRESS }}:/app
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DIGITAL_OCEAN_IP_ADDRESS }} << 'ENDSSH'
            cd /app
            source .env
            mkdir -p .envs/.production
            echo "${{secrets.MYWEBAPP_DJANGO_ENV_BUILD }}" >> .envs/.production/.django
            echo "${{secrets.MYWEBAPP_POSTGRES_ENV_BUILD }}" >> .envs/.production/.postgres
            docker login ghcr.io -u $NAMESPACE -p $PERSONAL_ACCESS_TOKEN
            docker pull $WEB_IMAGE
            docker pull $TRAEFIK_IMAGE
            docker pull $POSTGRES_IMAGE
            docker compose -f production.yml up -d
          ENDSSH
```

staging.yml (a copy of the production.yml generated by Cookiecutter)
```
version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: mywebapp_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: mywebapp_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: mywebapp_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'

  redis:
    image: redis:6

  awscli:
    build:
      context: .
      dockerfile: ./compose/production/aws/Dockerfile
    env_file:
      - ./.envs/.production/.django
    volumes:
      - production_postgres_data_backups:/backups:z
```

production.yml (my current version of it, I have edited this several different ways to try to get it to work)
```
version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  django:
    build:
      context: ./app
      dockerfile: compose/production/django/Dockerfile
    image: mywebapp_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: ./app
      dockerfile: compose/production/postgres/Dockerfile
    image: mywebapp_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: ./app
      dockerfile: compose/production/traefik/Dockerfile
    image: mywebapp_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'

  redis:
    image: redis:6

  awscli:
    build:
      context: ./app
      dockerfile: compose/production/aws/Dockerfile
    env_file:
      - ./.envs/.production/.django
    volumes:
      - production_postgres_data_backups:/backups:z
```
