### DISCUSSION TITLE
Code quality packages in local.txt

### DISCUSSION THREAD

**Discussion by jkaeske** [cookiecutter/cookiecutter-django#4820] [General]
Hey there,

I was wondering why the code quality tools like black and isort are listed additionally in the local.txt file.
They are specified in the pre-commit config file with the according versions.
That should be enough, right, or am I missing something?

Thanks a lot!

**Comment by browniebroke** [comment]
Great question! 

It should be enough, yes: for my personal projects, I moved away from specifying these in my local deps. However, on a team project I'm working on, most people use VSCode with devcontainers and they run these tools inside their containers, as opposed to on the host machine, like I do.

 I'm curious to hear what the community does and if there are other pros and cons...

**Comment by foarsitter** [comment]
In using these tools outside of `pre-commit` so therefore I like to have them locally. 

For some other projects `pre-commit` even points to the local executables like this: 

```
repos:
  - repo: local
    hooks:
      - id: bandit
        name: bandit
        entry: bandit
        language: system
        types: [python]
        require_serial: true
        args: ["-c", "bandit.yml"]
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        require_serial: true
```

In the end I don't care about it as long it gives me the correct outcome.
