### DISCUSSION TITLE
Letsencrypt can't find .well-known route because port 80 redirect to 443 after SSL is expired

### DISCUSSION THREAD

**Discussion by gjae** [cookiecutter/cookiecutter-django#5297] [Q&A] [answered]
## What happened?
When traefik tries renew the ssl certificate, letsencrypt should send request to domain.com/.well-known/.... but currently the certificated is expired therefore the request to /.../.well-known can't responses with status 200.

**Comment by luzfcb** [comment]
@gjae Thank you for opening an issue, however you did not respect our issue template, and did not provide any useful information (such as anonymized error logs) to help us help you.

**Reply by gjae** [reply]
Hey @luzfcb , thanks for answer. The context it's :

The LE certificate was expired, when the traefik's container tries renew it faile the authorization (at  least, that's I understand), when LE tries check the challenge sending a request to https://domain.com/.well-known/acme/..... can't make it. Trying acces to that route from browser  jump me a browser's message talking about the connection isn't private.

production/traefik.yml:

```yaml
log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"
    http:
      # https://docs.traefik.io/routing/entrypoints/#entrypoint
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    # https
    address: ":443"


certificatesResolvers:
  letsencrypt:
    # https://docs.traefik.io/master/https/acme/#lets-encrypt
    acme:
      email: "mymail@gmail.com"
      storage: /etc/traefik/acme/acme.json
      # https://docs.traefik.io/master/https/acme/#httpchallenge
      httpChallenge:
        entryPoint: web

http:
  routers:
    web-secure-router:
      rule: "Host(`host.app`) || PathPrefix(`/media/`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    web-media-router:
      rule: '(Host(`host.app`) || Host(`host.app`)) && PathPrefix(`/media/`)'
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django-media
      tls:
        certResolver: letsencrypt

  middlewares:
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000
    django-media:
      loadBalancer:
        servers:
          - url: http://nginx:80

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
````

Nginx settings
```nginx
upstream django-web {
    server django:5000;
}

server {
    listen 80;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    location / {
         proxy_pass http://django-web;

         proxy_set_header   Host $host;
         proxy_set_header   X-Real-IP $remote_addr;
         proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header   X-Forwarded-Host $server_name;
    }

  location /media/ {
    alias /usr/share/nginx/media/;
  }
}
````

Output from both containers of traefik and nginx
````bash
traefik-1       | time="2024-08-13T16:03:32Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yml"
traefik-1       | time="2024-08-13T16:03:32Z" level=info msg="Traefik version 2.2.11 built on 2020-09-07T14:12:48Z"
traefik-1       | time="2024-08-13T16:03:32Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/contributing/data-collection/\n"
traefik-1       | time="2024-08-13T16:03:32Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
traefik-1       | time="2024-08-13T16:03:32Z" level=info msg="Starting provider *file.Provider {\"watch\":true,\"filename\":\"/etc/traefik/traefik.yml\"}"
traefik-1       | time="2024-08-13T16:03:32Z" level=info msg="Starting provider *acme.Provider {\"email\":\"gjavilae@gmail.com\",\"caServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"storage\":\"/etc/traefik/acme/acme.json\",\"keyType\":\"RSA4096\",\"httpChallenge\":{\"entryPoint\":\"web\"},\"ResolverName\":\"letsencrypt\",\"store\":{},\"ChallengeStore\":{}}"
traefik-1       | time="2024-08-13T16:03:32Z" level=info msg="Testing certificate renew..." providerName=letsencrypt.acme
traefik-1       | time="2024-08-13T16:03:32Z" level=info msg="Starting provider *traefik.Provider {}"
traefik-1       | time="2024-08-13T16:03:32Z" level=info msg="Renewing certificate from LE : {Main:myhostdomain.app SANs:[]}" providerName=letsencrypt.acme
nginx-1         | 2024/08/13 16:03:34 [error] 8#8: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 23.178.112.210, server: , request: "GET /.well-known/acme-challenge/J3yZmmHCDzjpzh7ao6-gOY86jBb9NbOx8TQ22aIBzgs HTTP/1.1", upstream: "http://172.19.0.5:5000/.well-known/acme-challenge/J3yZmmHCDzjpzh7ao6-gOY86jBb9NbOx8TQ22aIBzgs", host: "myhostdomain.app"
nginx-1         | 23.178.112.210 - - [13/Aug/2024:16:03:34 +0000] "GET /.well-known/acme-challenge/J3yZmmHCDzjpzh7ao6-gOY86jBb9NbOx8TQ22aIBzgs HTTP/1.1" 502 157 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
````

production.yml

```yaml
version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: hostname_production_django
    volumes:
      - production_django_media:/app/hostname/media
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: hostname_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: hostname_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"

  redis:
    image: redis:6

  celeryworker:
    <<: *django
    image: hostname_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: hostname_production_celerybeat
    command: /start-celerybeat

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: hostname_production_nginx
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
    ports:
      - "0.0.0.0:80:80"
 ````
Could you help me, please?
