### ISSUE TITLE
Docker Version 18.06.0 migration not apply after reload in pycharm

### ISSUE THREAD

**Issue by Arti3DPlayer** [cookiecutter/cookiecutter-django#1779]
## What happened?
On old version of docker 13, after I did a model changes and have a running server with pycharm `runserver` command in new terminal window I do:

```
docker-compose -f local.yml run django python manage.py makemigrations
docker-compose -f local.yml run django python manage.py migrate
```

Then server automatically restarts and was fine. But with new version, I get:

> You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): booking.
> Run 'python manage.py migrate' to apply them.

To apply migration I should stop all containers, do `build` and only then I can use new db schema.

Also to completely stop the server I need to do `docker-compose stop` twice. First time stops only `postgres` container, and on second time stop all other containers

```
docker-compose -f local.yml stop
Stopping my_project_postgres_1 ... done
admin:my_project artem$ docker-compose -f local.yml stop
Stopping my_project_firefox_node_1_1 ... done
Stopping my_project_celerybeat_1     ... 
Stopping my_project_celeryworker_1   ... 
Stopping my_project_hub_1            ... done
Stopping my_project_redis_1          ... 
Stopping my_project_postgres_1       ... 
```

My docker-compose file:

```
version: '2'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: abs_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: abs_production_postgres
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:3.2

  celeryworker:
    <<: *django
    image: abs_local_celeryworker
    depends_on:
      - redis
      - postgres

    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: abs_local_celerybeat
    depends_on:
      - redis
      - postgres

    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports: []
    command: /start-celerybeat
```
