### ISSUE TITLE
Using cookiecutter-django with sites framework 

### ISSUE THREAD

**Issue by crabbitqq** [cookiecutter/cookiecutter-django#2095]
I'm trying to  serve two simple sites (with one static page for each site, with one global template) using cookiecutter-django with docker. Could you advise - how to configure it to serve 2 sites (if that's possible at all)? 
At this moment I can see only one "default" site, the second one is just secured with ssl.
Thanks.

**Comment by foarsitter** [comment]
For a side project I did this once. Roughly it involves two steps

- add an extra service to local.yml and production.yml 
- duplicatie the settings files and serve the newly added docker service with these 

This is what I have made from my local.yml (without the extra services):
```
services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: sites_local_django
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: /start
    ports:
      - "8000:8000"
    environment:
      - DJANGO_PORT=8000
      - DJANGO_SETTINGS_MODULE=config.settings.jelmertnl.local
  apifrl:
    <<: *django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: sites_local_django_api_frl
    ports:
      - "9000:9000"
    environment:
      - DJANGO_PORT=9000
      - DJANGO_SETTINGS_MODULE=config.settings.apifrl.local
```
Don't forget to add `${DJANGO_PORT}` and `${DJANGO_SETTINGS_MODULE}` to compose/local/django/start and change the 'SITE_ID', `WSGI_APPLICATION`, `ROOT_URLCONF` in your.
