### ISSUE TITLE
Race condition causing celerybeat and celeryworker to fail

### ISSUE THREAD

**Issue by malefice** [cookiecutter/cookiecutter-django#2727]
## What happened?

There is a race condition where `celerybeat` and/or `celeryworker` services will fail to start if the `django-celery-beat` migrations have not run. Bringing up the stack up again once those migrations have run will resume normally as expected.

## What should've happened instead?

While this can only occur under specific conditions (usually first run), it is best to have a guarantee that all services will be up and running 100% out-of-the-box. The `celerybeat` and/or `celeryworker` services should have a health check in its entrypoint script prior to running its command script. I personally have some code for this if you guys are interested, but I want to hear your thoughts first.

## Steps to reproduce

Tested on Ubuntu 18.04.4 LTS, Docker Engine version 19.03.12, docker-compose version 1.17.1

1. Create a new project from this template as you normally would but with docker and celery support.
2. Build and bring the whole stack up. The race condition usually shows up for me on the first run.
3. If it did not trigger the first time, then drop the database volume, and bring up the stack. You may need to repeat this step multiple times. 

## Some screenshots

![image](https://user-images.githubusercontent.com/7114869/89512537-f2e8ca80-d805-11ea-8ed4-1665ad2102dc.png)

![image](https://user-images.githubusercontent.com/7114869/89512661-1dd31e80-d806-11ea-8dca-857a6184bd4c.png)

**Comment by browniebroke** [comment]
Thanks for the great explanations in this bug report. It would be nice to fix it, yes. You're saying you have some code to fix it, I'd be interested in knowing more about your solution?

**Comment by malefice** [comment]
I am currently using `manage.py showmigrations app_name` to do this. It lists down all the migrations for the app, and a migration file has not yet been applied if `[ ]` is present like so:

![image](https://user-images.githubusercontent.com/7114869/89516939-a3a59880-d80b-11ea-9f4b-742150d0a806.png)


To ensure that all the migrations for `django_celery_beat` have run properly, we can grep the output of the command. This was how I did it. 

```bash
django_celery_migrations_complete() {
  count=$(python manage.py showmigrations django_celery_beat | grep '\[ \]' | wc -l)
  if [[ $count -eq 0 ]]; then
      return 0
  fi
    return 1
}

until django_celery_migrations_complete; do
  >&2 echo 'Waiting for Django Celery migrations to complete...'
  sleep 5
done
>&2 echo 'Django Celery migrations have been applied'
```

The only thing I cannot avoid is a little code duplication. Since this requires database access, the excerpt above must be preceded by the same postgres health check present in the django service's entrypoint script. I am not sure how to keep things DRY, so I implemented it such that I have a separate entrypoint script for the django service, and another entrypoint script for the celery services like so:

```
# Inside docker-compose file:

  celerybeat:
    <<: *django
    image: celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    entrypoint: /celery-entrypoint
    command: /start-celerybeat

  celeryworker:
    <<: *django
    image: celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    entrypoint: /celery-entrypoint
    command: /start-celeryworker
```
