### ISSUE TITLE
domain.com redirected you too many times

### ISSUE THREAD

**Issue by AustinGilkison** [cookiecutter/cookiecutter-django#3090]
## What happened?
I have recently set up a Django project and am trying to deploy it to production but getting a:
> Page isn't working domain.com redirected you too many times

## What should've happened instead?
The page should load as it normally did in local.

* Host system configuration: 
    * OS:
        * Amazon Linux 2

**Comment by Afrowave** [comment]
Hi @AustinGilkison,

Did you assign the domain name when you were setting up the project?

**Comment by Andrew-Chen-Wang** [comment]
@AustinGilkison Did you wait to get a certificate for users to be able to connect to https in the first place? There's a possibility the certification failed.

**Comment by AustinGilkison** [comment]
Yes, The site is using a valid SSL. Once I removed the following from line 48 in compose/production/traefik/traefik.yml everything worked fine.
```
redirect:
      # https://docs.traefik.io/master/middlewares/redirectscheme/
      redirectScheme:
        scheme: https
        permanent: true
```
