### ISSUE TITLE
Serving media files with NGINX issue

### ISSUE THREAD

**Issue by maponzzi** [cookiecutter/cookiecutter-django#4209]
Hello Everyone,
I'm trying to enable serving media files in production using nginx, as @arrys solution on his PR [#2457](https://github.com/cookiecutter/cookiecutter-django/pull/2457) but it doesn't works for me.

I implemented manually this PR because when I ran cookiecutter installation, and I chose None as cloud server doesn't added nginx as media server. (I don't know why? because it's suppose this PR its already added to the master branch)

The only one modification I made was in /compose/production/django/Dockerfile, I added this line:
`RUN mkdir ${APP_HOME}/proveemax/media && chown django:django ${APP_HOME}/proveemax/media`

in order to create my own media folder with django:django as the owner:group, because in the PR doesn't include the media folder creation and when I build containers this media folder was created with root:root ownership, so my django app crashed when I tried to upload any file because doesn't have permissions to write on that folder.

At this moment, with my own media folder (as mentioned above) I can upload media files, even when I connect to nginx container, media files are created in the right folder, (/usr/share/nginx/media/ ready to be served) which means media volume is also working.

I think traefik router (web-media-router) it's not working, because when I request a media file I just got a 404 not found, and I can't see anything on nginx logs (I guess I should see the request at least)

Any Idea how to solve this ? or how to test if the traefik router it's working ?

_**/compose/production/traefik/traefik.yml**_
```yml
log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"
    http:
      # https://docs.traefik.io/routing/entrypoints/#entrypoint
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    # https
    address: ":443"

certificatesResolvers:
  letsencrypt:
    # https://docs.traefik.io/master/https/acme/#lets-encrypt
    acme:
      email: "..."
      storage: /etc/traefik/acme/acme.json
      # https://docs.traefik.io/master/https/acme/#httpchallenge
      httpChallenge:
        entryPoint: web

http:
  routers:
    web-secure-router:
      rule: "Host(`proveemaxindustrial.com`) || Host(`www.proveemaxindustrial.com`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    web-media-router:
      rule: "Host(`proveemaxindustrial.com`) && PathPrefix(`/media/`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django-media
      tls:
        certResolver: letsencrypt

  middlewares:
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    django-media:
      loadBalancer:
        servers:
          - url: http://nginx:80

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
```

**_production.yml_**
```yml
version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: proveemax_production_django
    volumes:
      - production_django_media:/app/proveemax/media

    depends_on:
      - postgres
      # - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: proveemax_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: proveemax_production_traefik
    depends_on:
      - django
      - nginx
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: proveemax_local_nginx
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro

  # redis:
  #   image: redis:6
```

**_/compose/production/django/Dockerfile_**
```dockerfile
ARG PYTHON_VERSION=3.10-slim-bullseye



# define an alias for the specfic python version used in this file.
FROM python:${PYTHON_VERSION} as python

# Python build stage
FROM python as python-build-stage

ARG BUILD_ENVIRONMENT=production

# Install apt packages
RUN apt-get update && apt-get install --no-install-recommends -y \
  # dependencies for building Python packages
  build-essential \
  # psycopg2 dependencies
  libpq-dev

# Requirements are installed here to ensure they will be cached.
COPY ./requirements .

# Create Python Dependency and Sub-Dependency Wheels.
RUN pip wheel --wheel-dir /usr/src/app/wheels  \
  -r ${BUILD_ENVIRONMENT}.txt


# Python 'run' stage
FROM python as python-run-stage

ARG BUILD_ENVIRONMENT=production
ARG APP_HOME=/app

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV BUILD_ENV ${BUILD_ENVIRONMENT}

WORKDIR ${APP_HOME}

RUN addgroup --system django \
    && adduser --system --ingroup django django


# Install required system dependencies
RUN apt-get update && apt-get install --no-install-recommends -y \
  # psycopg2 dependencies
  libpq-dev \
  # Translations dependencies
  gettext \
  # cleaning up unused files
  && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
  && rm -rf /var/lib/apt/lists/*

# All absolute dir copies ignore workdir instruction. All relative dir copies are wrt to the workdir instruction
# copy python dependency wheels from python-build-stage
COPY --from=python-build-stage /usr/src/app/wheels  /wheels/

# use wheels to install python dependencies
RUN pip install --no-cache-dir --no-index --find-links=/wheels/ /wheels/* \
  && rm -rf /wheels/


COPY --chown=django:django ./compose/production/django/entrypoint /entrypoint
RUN sed -i 's/\r$//g' /entrypoint
RUN chmod +x /entrypoint


COPY --chown=django:django ./compose/production/django/start /start
RUN sed -i 's/\r$//g' /start
RUN chmod +x /start


# copy application code to WORKDIR
COPY --chown=django:django . ${APP_HOME}

RUN mkdir ${APP_HOME}/proveemax/media && chown django:django ${APP_HOME}/proveemax/media

# make django owner of the WORKDIR directory as well.
RUN chown django:django ${APP_HOME}


USER django

ENTRYPOINT ["/entrypoint"]
```

**_/compose/production/nginx/default.conf_**
```conf
server {
	listen       80;
	server_name  localhost;
	location /media/ {
		alias /usr/share/nginx/media/;
	}
}
```

## Additional details

* Host system configuration:
    * Version of cookiecutter CLI : Cookiecutter 2.1.1
    * OS name and version:

      ```bash
      Distributor ID:	Ubuntu
      Description:	Ubuntu 22.04.2 LTS
      Release:	22.04
      Codename:	jammy

      ```

    * Python version, run `python3 -V`: Python 3.10.6
    * Docker version (if using Docker), run `docker --version`: Docker version 23.0.1, build a5ee5b1
    * docker-compose version (if using Docker), run `docker-compose --version`: docker-compose version 1.29.2, build unknown
    * ...
* Options selected and/or [replay file](https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html):
    ```json
    {
      "cookiecutter": {
        "project_name": "ProveeMax",
        "project_slug": "provind",
        "description": "Proveemax",
        "author_name": "...",
        "domain_name": "proveemaxindustrial.com",
        "email": "...",
        "version": "0.1.0",
        "open_source_license": "Not open source",
        "timezone": "UTC",
        "windows": "n",
        "use_pycharm": "n",
        "use_docker": "y",
        "postgresql_version": "14",
        "cloud_provider": "None",
        "mail_service": "Other SMTP",
        "use_async": "n",
        "use_drf": "n",
        "frontend_pipeline": "None",
        "use_celery": "n",
        "use_mailhog": "n",
        "use_sentry": "n",
        "use_whitenoise": "y",
        "use_heroku": "n",
        "ci_tool": "None",
        "keep_local_envs_in_vcs": "y",
        "debug": "y",
        "_template": "https://github.com/arrys/cookiecutter-django",
        "_output_dir": "/Users/.../Dev/Python"
      }
    }
```
<summary>
Logs:
<details>
<pre>
$ cookiecutter https://github.com/cookiecutter/cookiecutter-django
project_name [Project Name]: ...
</pre>
</details>
</summary>

**Comment by browniebroke** [comment]
> The only one modification I made was in /compose/production/django/Dockerfile, I added this line: `RUN mkdir ${APP_HOME}/proveemax/media && chown django:django ${APP_HOME}/proveemax/media`
> 
> in order to create my own media folder with django:django as the owner:group, because in the PR doesn't include the media folder creation and when I build containers this media folder was created with root:root ownership, so my django app crashed when I tried to upload any file because doesn't have permissions to write on that folder.

I can reproduce that issue and the fix you mention works. Would you mind sending a pull request to fix it in the template? The file to fix is [here](https://github.com/cookiecutter/cookiecutter-django/blob/master/{{cookiecutter.project_slug}}/compose/production/django/Dockerfile).

> I think traefik router (web-media-router) it's not working, because when I request a media file I just got a 404 not found, and I can't see anything on nginx logs (I guess I should see the request at least)

I cannot reproduce that... I've uploaded the file in the admin, and the link rendered next to the file widget works fine.

**Comment by arrys** [comment]
@maponzzi do you see nginx starting worker processes on the nginx log?
Something like this:
```
2023/03/18 00:52:27 [notice] 1#1: using the "epoll" event method
2023/03/18 00:52:27 [notice] 1#1: nginx/1.17.8
2023/03/18 00:52:27 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4)
2023/03/18 00:52:27 [notice] 1#1: OS: Linux 5.15.90.1
2023/03/18 00:52:27 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2023/03/18 00:52:27 [notice] 1#1: start worker processes
2023/03/18 00:52:27 [notice] 1#1: start worker process 29
2023/03/18 00:52:27 [notice] 1#1: start worker process 30
...
```

If not, try changing the nginx container from `nginx:1.17.8-alpine` to `nginx:1.23-alpine` in [the Docker file for nginx](https://github.com/cookiecutter/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/production/nginx/Dockerfile) and see if that fixes the issue.

If you do see the workers being started, you can check if requests get router properly by trying to access URLs under `YOURDOMAIN/media/` . For example `curl https://proveemaxindustrial.com/media/nonexistent.png` and see if you see access logs. Both in the traefik container and the nginx one.

**Comment by maponzzi** [comment]
> I can reproduce that issue and the fix you mention works. Would you mind sending a pull request to fix it in the template? The file to fix is [here](https://github.com/cookiecutter/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/production/django/Dockerfile).

@browniebroke of course, it would be a pleasure send this pull request, but first I would like to be sure this works fine

> I cannot reproduce that... I've uploaded the file in the admin, and the link rendered next to the file widget works fine

just to be clear, when I upload a file using the admin, the link rendered next to the file widget works fine as well, but If I open that link to see the image in a new tab, this image doesn't shows, but I only see a django 404 not found page, if you click this image, can you see the image in a new tab ?

> If not, try changing the nginx container from nginx:1.17.8-alpine to nginx:1.23-alpine in [the Docker file for nginx](https://github.com/cookiecutter/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/production/nginx/Dockerfile) and see if that fixes the issue.

@arrys thanks for your help, first I couldn't see that nginx logs, after installing nginx:1.23-alpine I can see the starting worker processes on the nginx logs as you mention

> If you do see the workers being started, you can check if requests get router properly by trying to access URLs under YOURDOMAIN/media/ . For example curl https://proveemaxindustrial.com/media/nonexistent.png and see if you see access logs. Both in the traefik container and the nginx one.

However, I tested in browser and using curl https://proveemaxindustrial.com/media/nonexistent.png and nginx logs stay without activity, because it's not receiving the request, of course I tested an existing image as well and without success.

I tried: docker-compose -f production.yml exec nginx  curl http://localhost/media/images/groups/my_image.png and I received the curl response OK and of course nginx logs show the file I requested which tells me nginx container it's working fine, but for some reason as I mentioned, traefik router (web-media-router) it's not working fine

I couldn't enable accesLogs for traefik (only services logs are shown) to see more details

I added to production.yml:
```yml
services:
  traefik:
    command:
      - "--accesslog=true"
      - "--accesslog.filePath=/logs/access.log"
```

but I can't see the access logs, do you have an idea how to enable them ?

Thanks

**Comment by browniebroke** [comment]
> just to be clear, when I upload a file using the admin, the link rendered next to the file widget works fine as well, but If I open that link to see the image in a new tab, this image doesn't shows, but I only see a django 404 not found page, if you click this image, can you see the image in a new tab ?

When I wrote "the link works fine", I meant that I can open it in a new tab, yes.

**Comment by edwardigarashi** [comment]
try setting priority in your traefix.yml
https://doc.traefik.io/traefik/routing/routers/#priority

**Comment by vrychkov-repay** [comment]
I have the same issue

**Comment by bob-r** [comment]
I have the same issue with the latest version. No changes to dockerfiles. Empty nginx logs.

**Comment by arrys** [comment]
I think @edwardigarashi might be onto something. 
The rule for `web-media-router` needs to have priority over the rule for `web-secure-router`.
Traefik looks at the rule length to determine this when no explicit priority is set.

These rules are defined in [this file (traefik.yml)](https://github.com/cookiecutter/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/production/traefik/traefik.yml).

Adding a high priority like 1000 (just has to be higher than the length of the rule in `web-secure-router`) will make Traefik prioritize this rule.
```
    web-media-router:
      rule: "Host(`{{ cookiecutter.domain_name }}`) && PathPrefix(`/media/`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django-media
      tls:
        certResolver: letsencrypt
      priority: 1000
```

Alternatively, you can manually set the priority for both rules. Which might be a better solution to merge in case this solves the issue. Or we could even add the `www` subdomain to the media router rule like this:
```
rule: "(Host(`{{ cookiecutter.domain_name }}`) || Host(`www.{{ cookiecutter.domain_name }}`)) && PathPrefix(`/media/`)"
```
This would always make the media router rule have priority when consistent with the `web-secure-router` rule.

@maponzzi This is definitely happening in your case.
Your first rule has a priority of 70 and the media rule has a priority of 56. So nothing will ever be sent to the media router.
