### ISSUE TITLE
Allow multiple imports on one line

### ISSUE THREAD

**Issue by mfosterw** [cookiecutter/cookiecutter-django#4880]
## Description

Remove the following from `pyproject.toml`:

```toml
[tool.ruff.lint.isort]
force-single-line = true
```

## Rationale

I've never heard of forcing every import to be on its own line, and I am concerned that doing so will lead import blocks to be unnecessarily long. I haven't heard of many arguments in favor of this style, but I am open to them if anyone disagrees.
