### ISSUE TITLE
How to change the traefik ports exposed by docker

### ISSUE THREAD

**Issue by 954-Ivory** [cookiecutter/cookiecutter-django#5851]
I needed to host multiple websites on the same server and forward the subdomains using external nginx.

So I tried to change the ports exposed by traefik, and stop external nginx, but only port 1443 worked.

How should I change it?

```yml
  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: commission_settlement_platform_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:1080:80'
      - '0.0.0.0:1443:443'
      - '0.0.0.0:1555:5555'
```

**Comment by browniebroke** [comment]
@954-Ivory please consider posting your solution if you resolved your problem

**Comment by 954-Ivory** [comment]
> [@954-Ivory](https://github.com/954-Ivory) please consider posting your solution if you resolved your problem

We need to synchronously change ports in: [traefik.yml](https://github.com/cookiecutter/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/production/traefik/traefik.yml)
```yml
entryPoints:
  web:
    # http
    address: ':1080'
    http:
      # https://doc.traefik.io/traefik/routing/entrypoints/#entrypoint
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    # https
    address: ':1443'

  flower:
    address: ':1555'
```
